### ISSUE TITLE
Play-ws Release

### ISSUE THREAD

**Issue by gmalouf** [scamandrill/scamandrill#23]
Just checking in when/if the next release will be cut and published supporting integration with the play framework?

**Comment by joelsonoda** [comment]
I've been running master in my company's applications for the last few months with great results (using play framework). We were planning on updating some of the documentation before we released, but I haven't made time to do that yet. Thanks for the reminder!

**Comment by graingert** [comment]
my company have just made the upgrade from 2.3 -> 2.4. and are embarking on 2.5 so I've sort of ignored this till then :p

**Comment by joelsonoda** [comment]
I suppose since the documentation is in github pages, we really could release before updating the documentation. I would still like to create the branch for a play 2.4 compatible version of the library so that we can release 2.4.0 and 2.5.0 at the same time (documentation should then be updated with instructions for both versions).

**Comment by gmalouf** [comment]
Naive question - can play-ws be used without running within play
framework?  The place where I am using this library is running an akka-http
web server/client pair.

**Comment by joelsonoda** [comment]
play-ws is a component of play framework. It can be included by itself. The current head of this project has play-ws as a dependency. 

You would need to make sure that you used a compatible version of akka-http since play-ws is built primarity on akka-http. 

You would either update to match the version used of akka-http used by play-ws or take your chances that the class signatures in your current version of akka-http match those expected by play-ws while excluding the transative akka-http dependency from scamandrill.

**Comment by graingert** [comment]
@gmalouf the only issue is for people using play. They have to have only one version of play-ws

**Comment by joelsonoda** [comment]
@graingert what all do we need to do before the release?

**Comment by graingert** [comment]
closing in favour of https://github.com/scamandrill/scamandrill/issues/29 where I have a roadmap
